# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-14 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs_applied',
            new_name='JobsApplied',
        ),
        migrations.AlterField(
            model_name='jobsapplied',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyJobs'),
        ),
    ]
